name: bikram_yoga_lib
description: Knihovna pro komunikaci s bikram Yoga. Knihovna nabízí registraci, login, získání informací o lekcích...
version: 0.2.0
repository: https://github.com/tpkowastaken/bikram_yoga_lib

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  html: ^0.15.4
  http: ^1.1.0

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^2.0.0
  test: ^1.21.0
