name: bikram_yoga_lib
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  html: ^0.15.4
  http: ^1.1.0
  # path: ^1.8.0

dev_dependencies:
  dotenv: ^4.2.0
  lints: ^2.0.0
  test: ^1.21.0
